package qa.combined_approach.rules;

public enum HornAlchoiqAxiomType {

	SUBSUME_CONCEPT_CONJUNCTION,
	FOR_ALL_ROLES_FROM_DOMAIN,
	EXISTS,
	AT_MOST_ONE,
	NOMINAL,
	ROLE_SUBSUMPTION,

	CONCEPT_ASSERTION, ROLE_ASSERTION,
	// TODO maybe they are not Alchoiq
	DIFFERENT_INDIVIDUALS_ASSERTION, SAME_INDIVIDUAL_ASSERTION;


}
